X=MsgBox("hi artem!",4+64,"<3")
X=MsgBox("I hope ur feeling well",3+48,"<3")
X=MsgBox("I hope ur having a wonderful christmas",3+16,"<3") 
X=MsgBox("I hope u got all the gifts u wanted!",1+64,"<3") 
X=MsgBox("I love you very much pretty girl (:",2+16,"<3") 
